const genres = {
  'Action Adventure': [
    'Action',
    'Action-Adventure',
    'Action-adventure, mystery',
    'Action-adventure, stealth',
    'Action-adventure, survival horror',
    'Action/Adventure',
    'Action-adventure',
    'Action-adventure game',
    'Action-adventure stealth',
    'Action-adventure survival',
    'Adventure',
    'Space combat simulator',
    'Adventure-Survival',
    'Open world action-adventure',
  ],
  'Action RPG': [
    'Action-RPG',
    'Action Role Playing Game',
    'Action Role-Playing',
    'Action Role-playing',
    'Action role-playing',
    'Action role-playing game',
    'Action-RPG',
    'Action-Role-playing game',
  ],
  'First-Person Shooter': [
    'Action Role-Playing Shooter',
    'Action role-playing, first-person shooter',
    'Tactical Shooter',
    'Action role-playing, shooter',
    'Action shooter',
    'FPS',
    'Action-adventure, FPS',
    'First Person Shooter',
    'Rail shooter virtual reality',
    'Role-playing shooter',
    'Rhythm Shooter',
    "Shoot 'em up",
    'Shooter',
    'Third Person Shooter',
    'Third-Person Shooter',
    'Third-person shooter',
    'Run and Gun',
    'Shooter game',
    'First-Person Shooter',
    'First-person shooter',
    'Third-person shooter, tower defense',
    'Top-down shooter',
  ],
  'Battle Royale': ['Battle Royale, FPS', 'Battle royale'],
  RPG: [
    'Role Playing',
    'Role playing',
    'Role-Playing',
    'Tactical role playing',
    'Tactical role-playing',
    'Role-Playing Game (RPG)',
    'Role-playing',
    'Role-playing game',
  ],
  'City Building': [
    'City Building Real-Time Strategy', 'City-building',
    'City-building, real-time strategy',
  ],
  'Deck Building': ['Deck Building'],
  Fighting: ['Fighting game', 'Fighting role-playing'],
  'Graphic Adventure': ['Graphic adventure'],
  'Hack and Slash': ['Hack and slash'],
  'Interactive Movie': [
    'Interactive movie',
    'Interactive drama',
    'Interactive drama survival horror',
  ],
  Racing: [
    'Kart racing',
    'Vehicle combat',
    'Vehicle simulation game',
    'Vehicular Combat',
  ],
  MMORPG: ['Massively multiplayer online role-playing'],
  MMO: [
    'Multiplayer Action Game',
    'Multiplayer action',
    'Multiplayer first-person shooter',
  ],

  Platformer: [
    'Platform game',
    'Action Platformer',
    'Platform-Adventure',
    'Metroidvania',
    'Platform-adventure game',
  ],
  Puzzle: ['Puzzle'],

  'Real-Time Strategy': [
    'Real-time strategy',
    'Real-time tactics, turn-based strategy',
    'Real-timestrategy',
  ],

  Sandbox: ['Sandbox'],

  Simulation: [
    'Simulation Adventure',
    'Simulation role-playing',
    'Construction and management simulation',
    'Cooking simulation',
  ],

  'Sports Simulation': ['Sports', 'Sports role-playing', 'Sports simulation'],
  Stealth: ['Stealth'],
  Strategy: [
    'Strategy RPG',
    'Turn-Based Strategy',
    'Turn-Based Tactics',
    'Turn-based strategy',
  ],

  Survival: ['Survival Horror', 'Survival horror'],
};

export default genres;