const publisher = {
        '2K Games': [],
        '2K Sports': [],
        '505 Games': [],
        'Activision Blizzard': [ 'Activision', 'Blizzard Entertainment'],
        'Amazon Game Studios': [],
        'Annapurna Interactive': [],
        'Arkane Studios': [],
        'Atlus': [],
        'Bandai Namco': ['Bandai Namco Games',  'Bandai Namco Entertainment',  'Namco Bandai'],
        'Bethesda': [ 'Bethesda Softworks'],
        'Bloober Team': [],
        'Bungie': ['Bungie/Activision'],
        'CD Projekt': [ 'CD Projekt RED', 'CD Projekt Red'],
        'Capcom': [],
        'Chucklefish': ['Chucklefish Games'],
        'Codemasters': [],
        'Crate Entertainment': [],
        'Creative Assembly': ['Creative Assembly/SEGA'],
        'D3 Publisher': [],
        'DC Comics': [],
        'Deep Silver': [],
        'Devolver Digital': [],
        'Double Fine Productions': [],
        'EA Dice': [],
        'Ebb Software': [],
        'Electronic Arts': ['EA Sports'],
        'Ember Lab': [],
        'Epic Games': [],
        'FYQD-Studio': [],
        'Firaxis Games': [],
        'FromSoftware': [],
        'Frontier Developments': [],
        'GSC Game World': [],
        'Game Freak': [],
        'Gearbox Publishing': [],
        'Gearbox Software': [],
        'Good Shepherd Entertainment': [],
        'Grasshopper Manufacture': [],
        'Guerilla Games': [],
        'Headbang Club': [],
        'Hello Games': [],
        'House House': [],
        'Housemarque': [],
        'IO Interactive': [],
        'Image & Form': [],
        'Insomniac Games': [],
        'Iron Gate AB': [],
        'Koei Tecmo': [],
        'Kojima Productions': [],
        'Konami': [],
        'Konami Digital Entertainment': [],
        'Larian Studios': [],
        'Marvel Entertainment': [],
        'Marvelous': [],
        'Matt Makes Games': ['Matt Makes Games Inc.'],
        'Microids': [],
        'Microsoft': [],
        'Microsoft Studios': [],
        'Mojang': [],
        'Mojang/Microsoft Studios': [],
        'Moon Studios': [],
        'Motion Twin': [],
        'Naughty Dog': [],
        'Neon Giant': [],
        'Neople': [],
        'Neostream Interactive': [],
        'Nihon Falcom': [],
        'Ninja Theory': [],
        'Nintendo': [],
        'Obsidian Entertainment': [],
        'PUBG Corporation': [],
        'Panic Inc.': [],
        'Paradox Interactive': [],
        'PlayStation Worldwide Studios': [],
        'Playdead': [],
        'PopCap Games': [],
        'Private Division': [],
        'Psyonix': [],
        'Quantic Dream': [],
        'Rebellion Developments': [],
        'Rockstar Games': [],
        'SCS Software': [],
        'SEGA': [],
        'Sam Barlow': [],
        'Sega': [],
        "Shin'en Multimedia": [],
        'Sidebar Games': [],
        'Smilegate Entertainment': [],
        'Sony Interactive Entertainment': [ 'Sony Computer Entertainment'],
        'Sony Santa Monica': [],
        'Square Enix': [],
        'StudioMDHR': [],
        'Subset Games': [],
        'Sucker Punch Productions': [],
        'Sumo Digital': [],
        'SuperGiant Games': [ 'Supergiant Games'],
        'THQ Nordic': [],
        'TaleWorlds Entertainment': [],
        'Team Cherry': [],
        'Team17': ['Team17 Digital Ltd'],
        'Techland': [],
        'Telltale Games': [],
        'Thatgamecompany': [],
        'The Coalition': [],
        'Thekla, Inc.': [],
        'Thunder Lotus Games': [],
        'Toby Fox': [],
        'Torn Banner Studios': [],
        'Turn 10 Studios': [],
        'Ubisoft': [ 'Ubisoft Blue Byte',   'Ubisoft Toronto'],
        'Unknown Worlds Entertainment': [],
        'Valve': [],
        'Valve Corporation': [],
        'Warner Bros. Interactive Entertainment': [],
        'Xbox Game Studios': [],
        'ZA/UM': [],
        'miHoYo': [],
};

export default publisher;