const tags = [
    '2D',
    'Fighting',
    'Platformer',
    "Retro",
    'Action',
    'Action Adventure',
    'Action RPG',
    'Adventure',
    'Anime',
    'Arcade',
    'Art',
    'Assassination',
    'Augmented Reality',
    'Base Building',
    'Battle Royale',
    'Building',
    'Card Game',
    'Cars',
    'Castlevania',
    'Celtic',
    'Challenging',
    'Cinematic Choices',
    'Horror',
    'Remake',
    'Co-Op',
    'Cold War',
    'Collectibles',
    'Comedy',
    'Comedy',
    'Competitive',
    'Multiplayer',
    'Simulation',
    'Cooperative',
    'Crafting',
    'Creative',
    'Crossover',
    'Customization',
    'Cyberpunk',
    'Dark fantasy',
    'Difficult',
    'Disney',
    'Dragons',
    'Driving',
    'Dungeon Crawler',
    'Dystopia',
    'Fantasy',
    'Exploration',
    'FPS',
    'Family Friendly',
    'Fantasy',
    'Farming',
    'Combat',
    'Female Protagonist',
    'Fighting',
    'First-Person Shooter',
    'Football',
    'Free-to-Play',
    'Futuristic',
    'Gangster',
    'Ghosts',
    'Giant Eagle',
    'Gore',
    'Strategy',
    'Greek Mythology',
    'Hack and Slash',
    'Historical',
    'Horror',
    'Indie',
    'Interactive Movie',
    'JRPG',
    'Japan',
    'Local Co-op',
    'Loot',
    'MMORPG',
    'Magic',
    'Martial Arts',
    'Massive Battles',
    'Medieval',
    'Metroidvania',
    'Military',
    'Monster',
    'Multiplayer',
    'Music',
    'Mystery',
    'Mythology',
    'Exploration',
    'Open World',
    'Parkour',
    'Party',
    'Pixel Art',
    'Platformer',
    'Pokemon',
    'Police',
    'Post-Apocalyptic',
    'Procedurally Generated Content',
    'Puzzle',
    'Puzzle-platformer',
    'Puzzle-solving',
    'RPG',
    'Racing',
    'Realistic',
    'Remake',
    'Resource Management',
    'Retro',
    'Robots',
    'Roguelike',
    'Role Playing',
    'Romance',
    'Samurai',
    'Sandbox',
    'Sci-fi',
    'Side Scroller',
    'Simulation',
    'Soulslike',
    'Space',
    'Stealth',
    'Steampunk',
    'Story Rich',
    'Strategy',
    'Superhero',
    'Superpowers',
    'Surreal',
    'Survival',
    'Tactical',
    'Tactical Espionage',
    'Team-based',
    'Theme Park',
    'Third-Person',
    'Thriller',
    'Time Travel',
    'Trading Card Game',
    'Treasure Hunting',
    'Turn-based',
    'Underwater',
    'Unique Art Style',
    'VR',
    'Vikings',
    'Village Builder',
    'Violence',
    'Virtual Reality',
    'WWII',
    'Western',
    'XCOM-style',
    'Zombie Apocalypse',
    'Atmospheric',
    'Comedy',
    'Construction',
    'Dark',
    'Indie',
    'Isometric',
    'Management',
    'Metroidvania',
    'Military',
  ];
  

  export default tags;